version: 0.2

phases:
  install:
    commands:
      # Opcional: solo para depuración, muestra dónde se ejecuta CodeBuild
      - pwd
      - ls -l 
      
  build:
    commands:
      - echo Packaging deployment file...
  
  post_build:
    commands:
      - mkdir temp_zip
      - cp lambda_function.py temp_zip/
      - cd temp_zip
      - zip -r ../deploy_package.zip .
      - cd ..

artifacts:
  files:
    - deploy_package.zip
  discard-paths: no