version: 0.2

phases:
  install:
    commands:
      # Opcional: solo para debugging
      - ls -l 
      
  build:
    commands:
      - echo "Preparando archivos para el artefacto..."

artifacts:
  #El artefacto de salida de CodeBuild se llamará "lambda_function.py"
  files:
    - lambda_function.py  # Especificamos solo el archivo de código
  discard-paths: no